version: '3'

services:
  # 1. service
  own-mysql:
    container_name: own-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
  # 2. service
  crud-mysql-vuejs:
    container_name: crud-mysql-vuejs
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - own-mysql